name: Java CI


on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main


jobs:

  build:

    runs-on: ubuntu-latest


    steps:

      # Get project code
      - name: Checkout repository
        uses: actions/checkout@v4


      # Install Java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'


      # Compile application files
      - name: Compile Java files
        run: |
          mkdir build
          javac -d build src/*.java


      # Compile test files
      - name: Compile tests
        run: |
          javac -cp "build:lib/junit-platform-console-standalone-1.10.0.jar" -d build test/*.java


      # Run JUnit tests
      - name: Run Tests
        run: |
          java -jar lib/junit-platform-console-standalone-1.10.0.jar \
          --class-path build \
          --scan-class-path